package com.druidpyrcel.biotech.finaldilution.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CONCENTRATION".
 */
public class Concentration {

    private Long id;
    private double amount;
    private ConcentrationType type;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Concentration() {
    }

    public Concentration(Long id) {
        this.id = id;
    }

    public Concentration(Long id, double amount, ConcentrationType type) {
        this.id = id;
        this.amount = amount;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public ConcentrationType getType() {
        return type;
    }

    public void setType(ConcentrationType type) {
        this.type = type;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
