package com.druidpyrcel.biotech.finaldilution.model;

import de.greenrobot.dao.DaoException;
import de.greenrobot.dao.converter.PropertyConverter;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS
// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "CONCENTRATION".
 */
public class Concentration {

    private Long id;
    private Double amount;
    private ConcentrationType type;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Concentration() {
    }

    public Concentration(Long id) {
        this.id = id;
    }

    public Concentration(Long id, Double amount, ConcentrationType type) {
        this.id = id;
        this.amount = amount;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public ConcentrationType getType() {
        return type;
    }

    public void setType(ConcentrationType type) {
        this.type = type;
    }

    // KEEP METHODS - put your custom methods here

    public enum ConcentrationType {
        PERCENTAGE(0),
        MOLAR(1),
        MILIMOLAR(2),
        MILIGRAM_PER_MILLILITER(3);

        private final int value;

        ConcentrationType(int value) {
            this.value = value;
        }

        public int getValue() {
            return value;
        }
    }

    public class ConcentrationConverter implements PropertyConverter<ConcentrationType, Integer> {
        @Override
        public ConcentrationType convertToEntityProperty(Integer databaseValue) {
            if (databaseValue == null) {
                return null;
            }
            for (ConcentrationType type : ConcentrationType.values()) {
                if (type.getValue() == databaseValue) {
                    return type;
                }
            }
            throw new DaoException("Can't convert ConcentrationType from database value: " + databaseValue);
        }

        @Override
        public Integer convertToDatabaseValue(ConcentrationType entityProperty) {
            if (entityProperty == null) {
                return null;
            }
            return entityProperty.getValue();
        }
    }
    // KEEP METHODS END

}
