package com.druidpyrcel.biotech.finaldilution.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig solutionDaoConfig;
    private final DaoConfig compoundDaoConfig;
    private final DaoConfig concentrationDaoConfig;
    private final DaoConfig componentDaoConfig;

    private final SolutionDao solutionDao;
    private final CompoundDao compoundDao;
    private final ConcentrationDao concentrationDao;
    private final ComponentDao componentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        solutionDaoConfig = daoConfigMap.get(SolutionDao.class).clone();
        solutionDaoConfig.initIdentityScope(type);

        compoundDaoConfig = daoConfigMap.get(CompoundDao.class).clone();
        compoundDaoConfig.initIdentityScope(type);

        concentrationDaoConfig = daoConfigMap.get(ConcentrationDao.class).clone();
        concentrationDaoConfig.initIdentityScope(type);

        componentDaoConfig = daoConfigMap.get(ComponentDao.class).clone();
        componentDaoConfig.initIdentityScope(type);

        solutionDao = new SolutionDao(solutionDaoConfig, this);
        compoundDao = new CompoundDao(compoundDaoConfig, this);
        concentrationDao = new ConcentrationDao(concentrationDaoConfig, this);
        componentDao = new ComponentDao(componentDaoConfig, this);

        registerDao(Solution.class, solutionDao);
        registerDao(Compound.class, compoundDao);
        registerDao(Concentration.class, concentrationDao);
        registerDao(Component.class, componentDao);
    }

    public void clear() {
        solutionDaoConfig.getIdentityScope().clear();
        compoundDaoConfig.getIdentityScope().clear();
        concentrationDaoConfig.getIdentityScope().clear();
        componentDaoConfig.getIdentityScope().clear();
    }

    public SolutionDao getSolutionDao() {
        return solutionDao;
    }

    public CompoundDao getCompoundDao() {
        return compoundDao;
    }

    public ConcentrationDao getConcentrationDao() {
        return concentrationDao;
    }

    public ComponentDao getComponentDao() {
        return componentDao;
    }

}
